//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prbd_1920_g04.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("prbd_1920_g04.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not kicked off.
        /// </summary>
        public static string BrowseMatch_Status {
            get {
                return ResourceManager.GetString("BrowseMatch_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visit team :.
        /// </summary>
        public static string CreateMatchView_Adversary {
            get {
                return ResourceManager.GetString("CreateMatchView_Adversary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date :.
        /// </summary>
        public static string CreateMatchView_Date {
            get {
                return ResourceManager.GetString("CreateMatchView_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Division :.
        /// </summary>
        public static string CreateMatchView_Division {
            get {
                return ResourceManager.GetString("CreateMatchView_Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home team :.
        /// </summary>
        public static string CreateMatchView_Home {
            get {
                return ResourceManager.GetString("CreateMatchView_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Place :.
        /// </summary>
        public static string CreateMatchView_Place {
            get {
                return ResourceManager.GetString("CreateMatchView_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse :.
        /// </summary>
        public static string CreatePlayersView_Adresse {
            get {
                return ResourceManager.GetString("CreatePlayersView_Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Age : .
        /// </summary>
        public static string CreatePlayersView_Age {
            get {
                return ResourceManager.GetString("CreatePlayersView_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email :.
        /// </summary>
        public static string CreatePlayersView_Email {
            get {
                return ResourceManager.GetString("CreatePlayersView_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Firstname :.
        /// </summary>
        public static string CreatePlayersView_Firstname {
            get {
                return ResourceManager.GetString("CreatePlayersView_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Height :.
        /// </summary>
        public static string CreatePlayersView_Height {
            get {
                return ResourceManager.GetString("CreatePlayersView_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JerseyNumber :.
        /// </summary>
        public static string CreatePlayersView_JerseyNumber {
            get {
                return ResourceManager.GetString("CreatePlayersView_JerseyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lastname : .
        /// </summary>
        public static string CreatePlayersView_Lastname {
            get {
                return ResourceManager.GetString("CreatePlayersView_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password :.
        /// </summary>
        public static string CreatePlayersView_Password {
            get {
                return ResourceManager.GetString("CreatePlayersView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Position:.
        /// </summary>
        public static string CreatePlayersView_Position {
            get {
                return ResourceManager.GetString("CreatePlayersView_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weight :.
        /// </summary>
        public static string CreatePlayersView_Weight {
            get {
                return ResourceManager.GetString("CreatePlayersView_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A player of this age category already owns this jersey.
        /// </summary>
        public static string Error_CombinationAgeAndJerseyNumber {
            get {
                return ResourceManager.GetString("Error_CombinationAgeAndJerseyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the combination of first and last name already exists.
        /// </summary>
        public static string Error_CombinationFirstAndLastName {
            get {
                return ResourceManager.GetString("Error_CombinationFirstAndLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This date match existe, please select other.
        /// </summary>
        public static string Error_DateMatchExiste {
            get {
                return ResourceManager.GetString("Error_DateMatchExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not authorized !.
        /// </summary>
        public static string Error_DoesNotExist {
            get {
                return ResourceManager.GetString("Error_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à length must be &gt;= 10.
        /// </summary>
        public static string Error_LengthGreaterEqual10 {
            get {
                return ResourceManager.GetString("Error_LengthGreaterEqual10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à number must be &gt;= 2.
        /// </summary>
        public static string Error_LengthGreaterEqual2 {
            get {
                return ResourceManager.GetString("Error_LengthGreaterEqual2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à length must be &gt;= 3.
        /// </summary>
        public static string Error_LengthGreaterEqual3 {
            get {
                return ResourceManager.GetString("Error_LengthGreaterEqual3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à length must be &gt;= 8.
        /// </summary>
        public static string Error_LengthGreaterEqual8 {
            get {
                return ResourceManager.GetString("Error_LengthGreaterEqual8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à length must be &lt;= 10.
        /// </summary>
        public static string Error_LengthInferiorEqual10 {
            get {
                return ResourceManager.GetString("Error_LengthInferiorEqual10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à length must be &lt;= 100.
        /// </summary>
        public static string Error_LengthInferiorEqual100 {
            get {
                return ResourceManager.GetString("Error_LengthInferiorEqual100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à length must be &lt;= 20.
        /// </summary>
        public static string Error_LengthInferiorEqual20 {
            get {
                return ResourceManager.GetString("Error_LengthInferiorEqual20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à length must be &lt;= 40.
        /// </summary>
        public static string Error_LengthInferiorEqual40 {
            get {
                return ResourceManager.GetString("Error_LengthInferiorEqual40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à number must be &gt;= 1.
        /// </summary>
        public static string Error_NumberGreaterEqual1 {
            get {
                return ResourceManager.GetString("Error_NumberGreaterEqual1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à number must be &gt;= 165.
        /// </summary>
        public static string Error_NumberGreaterEqual165 {
            get {
                return ResourceManager.GetString("Error_NumberGreaterEqual165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à number must be &gt;= 60.
        /// </summary>
        public static string Error_NumberGreaterEqual60 {
            get {
                return ResourceManager.GetString("Error_NumberGreaterEqual60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à number must be &gt;= 7.
        /// </summary>
        public static string Error_NumberGreaterEqual7 {
            get {
                return ResourceManager.GetString("Error_NumberGreaterEqual7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à number must be &lt;= 110.
        /// </summary>
        public static string Error_NumberInferiorEqual110 {
            get {
                return ResourceManager.GetString("Error_NumberInferiorEqual110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à number must be &lt;= 210.
        /// </summary>
        public static string Error_NumberInferiorEqual210 {
            get {
                return ResourceManager.GetString("Error_NumberInferiorEqual210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à number must be &lt;= 50.
        /// </summary>
        public static string Error_NumberInferiorEqual50 {
            get {
                return ResourceManager.GetString("Error_NumberInferiorEqual50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à number must be &lt;= 99.
        /// </summary>
        public static string Error_NumberInferiorEqual99 {
            get {
                return ResourceManager.GetString("Error_NumberInferiorEqual99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à required.
        /// </summary>
        public static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wrong password.
        /// </summary>
        public static string Error_WrongPassword {
            get {
                return ResourceManager.GetString("Error_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string LoginView_Cancel {
            get {
                return ResourceManager.GetString("LoginView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string LoginView_Login {
            get {
                return ResourceManager.GetString("LoginView_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you don&apos;t have a Secretary login, please contact your administrator !.
        /// </summary>
        public static string LoginView_Message {
            get {
                return ResourceManager.GetString("LoginView_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password:.
        /// </summary>
        public static string LoginView_Password {
            get {
                return ResourceManager.GetString("LoginView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pseudo:.
        /// </summary>
        public static string LoginView_Pseudo {
            get {
                return ResourceManager.GetString("LoginView_Pseudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E-Club Manager.
        /// </summary>
        public static string LoginView_Title {
            get {
                return ResourceManager.GetString("LoginView_Title", resourceCulture);
            }
        }
    }
}
